FORMAT: 1A
HOST: http:/api.tap.shmn7iii.net

# Tap API Document

## About
**REST API for [Tap!](https://tap.shmn7iii.net)**

Tap! is a service that makes publishing NFTs easier, more convenient, and more understandable, with the goal of lowering the barriers to NFTs, making them more accessible, and promoting their use in the general public, thereby further developing the NFT industry.

This service was created within the "ChalleChara", and its actual use is yet to be determined. Also, we do not guarantee the tokens. For more information, please refer to the Terms of Use and Privacy Policy. -  Tap! Team.

[[GitHub] Tap-Team/tap-api](https://github.com/Tap-Team/tap-api)

## Usage
REST APIのイメージで作ってるからその感じで。

::: warning
### Caution
チームメンバー向けに書いてるだけだよ公開する意図はないよ
:::

# Group TapUser
### 一覧 [GET /users/{num}]
ユーザーの一覧を表示する。 `{num}` を指定することで任意の数だけ直近のユーザーを取得可能。

::: note
## Note
たぶん使い所ありませんデバッグ用です。
:::

+ Parameters
    + num: `5` (optional, int) - 取得ユーザー数


+ Response 200
    + Body
        ```
        {
            "status": 200,
            "message": "Success! tokens#index",
            "data": [
                {
                "uid": "init",
                "wallet_id": "9baae4db7398a411964cc78e13061954",
                "created_at": "2021-09-23T03:31:02.407Z",
                "updated_at": "2021-09-23T03:31:02.407Z"
                },
                {
                "uid": "testuid",
                "wallet_id": "6026f2fe82b4f805e82a51c8e00255fc",
                "created_at": "2021-09-23T03:32:34.390Z",
                "updated_at": "2021-09-23T03:32:34.390Z"
                }
            ]
        }
        ```
+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```

### 情報取得 [GET /users/info/{uid}]
ユーザーの情報とトークン一覧を表示する。

+ Parameters
    + uid: `9ao4s2L120RiGkKwJEKojL5uw7H1` (required, string) - Firabase Auth's uid.

+ Response 200
    + Body
        ```
        {
            "status": 200,
            "message": "Success! users#index/testuid",
            "data": {
                "uid": "testuid",
                "wallet_id": "6026f2fe82b4f805e82a51c8e00255fc",
                "created_at": "2021-09-23T03:32:34.390Z",
                "updated_at": "2021-09-23T03:32:34.390Z",
                "tokens": [
                "c36c996fd8404937baad81f6a07784a53b5d6af87b938ea7d38a76abbaea4df1ec",
                "c362a79394a8b5f75ca45b4bcb0944ef1f263fde945c134b35701b98624742e528",
                "c311839dbbf214fda45294d0fb32f8d7ea6641f2123acf1b1be0d1fd446e3a7bbf"
                ]
            }
        }
        ```
+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```


### 登録 [POST /users]
新規ユーザを登録する


+ Request (application/json)
	+ Body
        ```
        {
            "uid": "KOKO_NI_UID_WO_IRERU_YO"
        }
        ```

+ Response 200
    + Body
        ```
        {
            "status": "200",
            "message": "Success! users#create",
            "data": "No contents"
        }
        ```

+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```


### 更新 [PUT /users/{uid} ]
ユーザーを更新する。

::: note
## Note
確実に使い所ありません。デバッグ用です。実はデバッグもしてません。
:::

+ Parameters
    + uid: `9ao4s2L120RiGkKwJEKojL5uw7H1` (required, string) - Firabase Auth's uid.


+ Request (application/json)
	+ Body
        ```
        {
            "uid": "KOKO_NI_UID_WO_IRERU_YO",
            "wallet_id": "KOKO_HA_WALLET_ID_WO_IRERU_YO"
        }
        ```

+ Response 200
    + Body
        ```
        {
            "status": "200",
            "message": "Success! users#update",
            "data": "No contents"
        }
        ```

+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```


### 削除 [DELETE /users/{uid} ]
ユーザーを削除する

+ Parameters
    + uid: `9ao4s2L120RiGkKwJEKojL5uw7H1` (required, string) - Firabase Auth's uid.

+ Response 200
    + Body
        ```
        {
            "status": "200",
            "message": "Success! users#delete",
            "data": "No contents"
        }
        ```

+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```


# Group TapToken
トークンに関するリソース

### 一覧 [GET /tokens/{num}]
トークンの一覧を取得する。 `{num}` を指定することで任意の数だけ直近のトークンを取得可能。

+ Parameters
    + num: `5` (optional, int) - 取得トークン量

+ Response 200
    + Body
        ```
        {
            "status": 200,
            "message": "Success! tokens#index",
            "data": [
                {
                "token_id": "c36c996fd8404937baad81f6a07784a53b5d6af87b938ea7d38a76abbaea4df1ec",
                "data": "gs://tap-f4f38.appspot.com/tmp/testttttttttttttt.png",
                "created_at": "2021-09-23T03:45:14.581Z",
                "updated_at": "2021-09-23T03:45:14.581Z"
                },
                {
                "token_id": "c362a79394a8b5f75ca45b4bcb0944ef1f263fde945c134b35701b98624742e528",
                "data": "gs://tap-f4f38.appspot.com/tmp/testttttttttttttt.png",
                "created_at": "2021-09-23T03:48:43.521Z",
                "updated_at": "2021-09-23T03:48:43.521Z"
                },
                {
                "token_id": "c311839dbbf214fda45294d0fb32f8d7ea6641f2123acf1b1be0d1fd446e3a7bbf",
                "data": "gs://tap-f4f38.appspot.com/tmp/testttttttttttttt.png",
                "created_at": "2021-09-23T03:50:02.078Z",
                "updated_at": "2021-09-23T03:50:02.078Z"
                }
            ]
        }
        ```
+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```

### 情報取得 [GET /tokens/info/{token_id}]
指定トークンの情報を取得する。

+ Parameters
    + token_id: `9ao4s2L120RiGkKwJEKojL5uw7H1` (required, string) - Token's id

+ Response 200
    + Body
        ```
        {
            "status": 200,
            "message": "Success! tokens#info",
            "data": {
                "token_id": "c36c996fd8404937baad81f6a07784a53b5d6af87b938ea7d38a76abbaea4df1ec",
                "data": "gs://tap-f4f38.appspot.com/testttttttttttttt.png",
                "created_at": "2021-09-23T03:45:14.581Z",
                "updated_at": "2021-09-23T03:45:14.581Z"
            }
        }
        ```

+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```

### 発行 [POST /tokens]
トークンを発行する。

+ Request (application/json)
	+ Body
        ```
        {
            "uid": "KOKO_NI_UID_WO_IRERU_YO",
            "data": "KOKO_HA_DATA_NO_URI_GA_HAIRU_YO"
        }
        ```

+ Response 200
    + Body
        ```
        {
            "status": "200",
            "message": "Success! tokens#create",
            "data": {
            	"token_id": "TOKEN_NO_ID_GA_KAETTE_KURU_YO"
            }
        }
        ```

+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```

### 移転 [PUT /tokens/{token_id}]
トークンを移転する。

+ Parameters
    + token_id: `9ao4s2L120RiGkKwJEKojL5uw7H1` (required, string) - Token's id

+ Request (application/json)
	+ Body
        ```
        {
            "sender_uid": "KOKO_NI_UID_WO_IRERU_YO",
            "receiver_uid": "KOKO_NI_UID_WO_IRERU_YO"
        }
        ```

+ Response 200
    + Body
        ```
        {
            "status": "200",
            "message": "Success! tokens#update",
            "data": {
            	"token_id": "TOKEN_NO_ID_GA_KAETTE_KURU_YO",
            	"txid": "KOKO_NI_TRANSACTION_ID_GA_HAIRU_YO"
            }
        }
        ```

+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```

### 焼却 [DELETE /tokens/{token_id}]
トークンを焼却する。

+ Parameters
    + token_id: `9ao4s2L120RiGkKwJEKojL5uw7H1` (required, string) - Token's id

+ Response 200
    + Body
        ```
        {
            "status": "200",
            "message": "Success! users#delete",
            "data": {
            	"token_id": "TOKEN_NO_ID_GA_KAETTE_KURU_YO",
            	"txid": "KOKO_NI_TRANSACTION_ID_GA_HAIRU_YO"
            }
        }
        ```

+ Response 500
    + Body
        ```
        {
            "status": "500",
            "message": "Internal Server Error",
            "data": "(error message)"
        }
        ```